name: Publish static Maven repo to GitHub Pages (no auth)

on:
  push:
    branches: [ main ]
    paths:
      - 'releases/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pages-maven-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Determine release directory, JAR and version
        id: rel
        run: |
          set -e
          REL_DIR="$(ls -td releases/*/ 2>/dev/null | head -1 | sed 's:/*$::')"
          if [ -z "$REL_DIR" ]; then
            echo "No release directory found under releases/"; exit 1
          fi

          JAR_PATH="$(ls "$REL_DIR"/*.jar 2>/dev/null | head -1 || true)"
          if [ ! -f "$JAR_PATH" ]; then
            echo "No JAR found under $REL_DIR"; exit 1
          fi

          if [ -f "$REL_DIR/release_version.txt" ]; then
            VERSION="$(tr -d ' \r\n' < "$REL_DIR/release_version.txt")"
          else
            FOLDER_TS="$(basename "$REL_DIR")"
            POM_VERSION=$( [ -f "$REL_DIR/pom_version.txt" ] && tr -d ' \r\n' < "$REL_DIR/pom_version.txt" || echo "0.0.0" )
            VERSION="${POM_VERSION}_${FOLDER_TS}"
          fi

          echo "rel_dir=$REL_DIR"       >> $GITHUB_OUTPUT
          echo "jar_path=$JAR_PATH"     >> $GITHUB_OUTPUT
          echo "version=$VERSION"       >> $GITHUB_OUTPUT

      - name: Publish static Maven repo under docs/maven (explicit POM, correct GAV)
        run: |
          set -e
          SITE_ROOT="docs/maven"
          mkdir -p "$SITE_ROOT"
          touch "docs/.nojekyll"

          VERSION="${{ steps.rel.outputs.version }}"

          # Clean previously published version to avoid stale POMs/JARs/metadata
          rm -rf "$SITE_ROOT/com/ab_tools/spring-mcp-starter-dist/$VERSION"

          # Create a minimal POM with correct coordinates
          TMP_POM="$(mktemp)"
          cat > "$TMP_POM" <<'POM'
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.ab_tools</groupId>
  <artifactId>spring-mcp-starter-dist</artifactId>
  <version>${version}</version>
  <packaging>jar</packaging>
  <name>spring-mcp-starter-dist</name>
  <description>Static Maven repo artifact for Spring MCP starter distribution</description>
</project>
POM

          # Replace ${version} placeholder with the computed version
          sed -i "s|\${version}|$VERSION|g" "$TMP_POM"

          # Deploy using the explicit POM file (avoids inference from JAR's embedded POM)
          mvn -B deploy:deploy-file \
            -DpomFile="$TMP_POM" \
            -Dfile="${{ steps.rel.outputs.jar_path }}" \
            -DrepositoryLayout=default \
            -Durl="file://$GITHUB_WORKSPACE/${SITE_ROOT}"

      - name: Commit and push Pages content
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/maven docs/.nojekyll
          git commit -m "Publish ${{ steps.rel.outputs.version }} to static Maven repo (docs/maven) with explicit minimal POM" || echo "No changes to commit"
          git push
